name: The Committee to Stop a Bad Cure
title: Committee to Stop a Bad Cure
description: Vote NO in Jackson County on Nov. 5th
excerpt: 32
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions:
    - smart
    - autolink
